name: delivery_app
description: Final delivery app
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  geolocator: ^13.0.1

flutter:
  uses-material-design: true
